import bpy
import math


print(bpy.context.area)
print(bpy.context.blend_data)
print(bpy.context.mode)
print(bpy.context.region)
print(bpy.context.region_data)
print(bpy.context.scene)
print(bpy.context.screen)
print(bpy.context.space_data)
print(bpy.context.tool_settings)
print(bpy.context.user_preferences)
print(bpy.context.window)
print(bpy.context.window_manager)
print("Screen context")
print(bpy.context.scene)
print(bpy.context.visible_objects)
print(bpy.context.visible_bases)
print(bpy.context.selectable_objects)
print(bpy.context.selectable_bases)
print(bpy.context.selected_objects)
print(bpy.context.selected_bases)
print(bpy.context.selected_editable_objects)
print(bpy.context.selected_editable_bases)
print(bpy.context.visible_bones)
print(bpy.context.editable_bones)
print(bpy.context.selected_bones)
print(bpy.context.selected_editable_bones)
print(bpy.context.visible_pose_bones)
print(bpy.context.active_bone)
print(bpy.context.active_base)
print(bpy.context.active_object)
print(bpy.context.object)
print(bpy.context.edit_object)
print(bpy.context.sculpt_object)
print()
print()
print()
print()
print()
print()
print()